name: "Deploy"
on:
  push:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    name: Deploy
    runs-on: 
      - self-hosted
      - deploy
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Create config,toml
        run: echo "${{ secrets.CONFIG_TOML }}" > config.toml

      - name: Deploy
        run: docker-compose up -d --build
